name: "Build Release"
on: 
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - { uses: actions/checkout@v2, with: { fetch-depth: 0 } }
      - {
          uses: madhead/read-java-properties@latest,
          id: all,
          with: {
            file: gradle.properties,
            all: true
          }
        }
      - {
          name: "Set up JDK 17",
          uses: actions/setup-java@v2,
          with: { distribution: "adopt", java-version: "17" },
        }
      - {
          name: "Build with Gradle",
          id: build,
          run: "chmod +x gradlew && ./gradlew build publish",
        }
      - name: "Publish maven to wandhoven.ddns.net"
        uses: appleboy/scp-action@master
        with:
          host: "wandhoven.ddns.net"
          username: ${{ secrets.SCP_MAVEN_USERNAME }}
          key: ${{ secrets.SCP_MAVENKEY }}
          source: "maven/"
          target: "/media/B/html/"
      - name: "Upload to CurseForge"
        uses: itsmeow/curseforge-upload@v3
        with:
          file_path: "build/libs/BlockHighlighting-${{ steps.all.outputs.minecraft_version }}-${{ steps.all.outputs.mod_version }}.jar"
          game_endpoint: "minecraft"
          relations: "fabric-api:requiredDependency"
          game_versions: "Minecraft 1.19:1.19.2,Java 17,Fabric"
          project_id: "770218"
          token: "${{ secrets.CF_API_TOKEN }}"
